### ISSUE TITLE
DAP models are not included in `prelude`

### ISSUE THREAD

**Issue by vlopes11** [codx-dev/dap-reactor#7]
**Describe the bug**
The models aren't included in the prelude of the crate. Example: `RestartArguments`

**To Reproduce**
N/A

**Expected behavior**
The prelude should export all usable types

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Daksh14** [comment]
Fixed by #6
